apiVersion: v1
kind: Service
metadata:
  name: helaayu
spec:
  ports:
  - name: gateway
    port: 5001
    protocol: TCP
    targetPort: 5001
  - name: usermanagement
    port: 5002
    protocol: TCP
    targetPort: 5002
  - name: paymentgateway
    port: 5005
    protocol: TCP
    targetPort: 5005 
  - name: ordermanagement
    port: 5008
    protocol: TCP
    targetPort: 5008
  - name: productmanagement
    port: 5003
    protocol: TCP
    targetPort: 5003
  - name: deliverymanagement
    port: 5007
    protocol: TCP
    targetPort: 5007
  - name: reviewmanagement
    port: 5006
    protocol: TCP
    targetPort: 5006  
  - name: cartmanagement
    port: 5004
    protocol: TCP
    targetPort: 5004    
  selector:
    app: helaayu
  type: LoadBalancer
status:
  loadBalancer: {}
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helaayu
  name: helaayu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helaayu
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: helaayu
    spec:
      containers:
      - name: gateway
        image: dreamseers2023/img_server_gateway
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
          protocol: TCP
        resources: {}
      - name: usermanagement
        image: dreamseers2023/img_server_user_management
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
          protocol: TCP
        resources: {}
      - name: paymentgateway
        image: dreamseers2023/img_server_payment_gateway
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
          protocol: TCP
        resources: {}
      - name: ordermanagement
        image: dreamseers2023/img_server_order_management
        imagePullPolicy: Always
        ports:
        - containerPort: 5008
          protocol: TCP
        resources: {}
      - name: productmanagement
        image: dreamseers2023/img_server_product_management
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
          protocol: TCP
        resources: {}
      - name: deliverymanagement
        image: dreamseers2023/img_server_delivery_management
        imagePullPolicy: Always
        ports:
        - containerPort: 5007
          protocol: TCP
        resources: {}
      - name: reviewmanagement
        image: dreamseers2023/img_server_review_management
        imagePullPolicy: Always
        ports:
        - containerPort: 5006
          protocol: TCP
        resources: {}
      - name: cartmanagement
        image: dreamseers2023/img_server_cart_management
        imagePullPolicy: Always
        ports:
        - containerPort: 5004
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}

# kubectl apply -f helaayu.yaml
# kubectl delete -f helaayu.yaml